package com.marketstrategy;

/**
 * Represents a trading signal generated by a strategy.
 * Contains information about the stock symbol, action (BUY/SELL), price,
 * the name of the strategy that generated the signal, and a reason.
 */
public class TradeSignal {
    /**
     * Defines the type of trading action.
     */
    public enum Action {
        /** Indicates a buy signal. */
        BUY,
        /** Indicates a sell (or short sell) signal. */
        SELL,
        /** Indicates a hold signal (currently unused but available for future strategies). */
        HOLD // Could be used if a strategy explicitly decides to hold
    }

    private String symbol;
    private Action action;
    private double price; // Price at which the signal is generated (e.g., LTP or Open)
    private String strategyName;
    private String reason;

    /**
     * Constructs a new TradeSignal.
     * @param symbol The stock symbol.
     * @param action The trading action (BUY/SELL).
     * @param price The price associated with the signal.
     * @param strategyName The name of the strategy generating this signal.
     * @param reason A descriptive reason for the signal.
     */
    public TradeSignal(String symbol, Action action, double price, String strategyName, String reason) {
        this.symbol = symbol;
        this.action = action;
        this.price = price;
        this.strategyName = strategyName;
        this.reason = reason;
    }

    /** @return The stock symbol. */
    public String getSymbol() {
        return symbol;
    }

    /** @return The trading action. */
    public Action getAction() {
        return action;
    }

    /** @return The price associated with the signal. */
    public double getPrice() {
        return price;
    }

    /** @return The name of the strategy that generated the signal. */
    public String getStrategyName() {
        return strategyName;
    }

    /** @return The reason or criteria for this signal. */
    public String getReason() {
        return reason;
    }

    @Override
    public String toString() {
        return String.format("TradeSignal{strategy='%s', symbol='%s', action=%s, price=%.2f, reason='%s'}",
                strategyName, symbol, action, price, reason);
    }
}
